name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure assets directory exists
        run: mkdir -p assets

      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: 13reath
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
